name: studies_app_flutter
description: A Flutter project converted from a native Android app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  provider: ^6.1.1

  floor: ^1.4.2
  sqflite: ^2.3.0

  dio: ^5.4.0
  json_annotation: ^4.8.1

  go_router: ^13.0.1

  shared_preferences: ^2.2.2

  crypto: ^3.0.3

  cupertino_icons: ^1.0.2

  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  floor_generator: ^1.4.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  test: ^1.24.9


flutter:
  uses-material-design: true
  generate: true